// bad-ui/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <main class="min-h-screen bg-gray-50">
      <app-chat></app-chat>
    </main>
  `,
  styles: []
})
export class AppComponent {
  title = 'chat-ui';
}

<main class="min-h-screen bg-gray-50">
  <app-chat></app-chat>
</main>

// ecommerce-react-app/src/App.tsx
import { Outlet } from 'react-router-dom';
import Navigation from './components/Navigation';

const App = () => {
  return (
    <div className="min-h-screen bg-gray-50">
      <Navigation />
      <main className="container mx-auto px-4 py-8 pt-24">
        <Outlet />
      </main>
    </div>
  );
};

export default App;
